### ISSUE TITLE
Cryptic NPE initializing scalac Global

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#120]
I'm getting the following error at weird times, even when there are no new .compilerconfig files to act on

```
20:30:43.565 ERROR l.c.LanguageServer$$anon$1 - null
java.lang.Throwable: null
	at scala.reflect.internal.BaseTypeSeqs.$init$(BaseTypeSeqs.scala:265)
	at scala.reflect.internal.SymbolTable.<init>(SymbolTable.scala:16)
	at scala.tools.nsc.symtab.SymbolTable.<init>(SymbolTable.scala:9)
	at scala.tools.nsc.Global.<init>(Global.scala:37)
	at scala.tools.nsc.interactive.Global.<init>(Global.scala:111)
	at scala.meta.languageserver.compiler.ScalacProvider$.newCompiler(ScalacProvider.scala:87)
	at scala.meta.languageserver.compiler.ScalacProvider.loadNewCompilerGlobals(ScalacProvider.scala:47)
	at scala.meta.languageserver.ScalametaLanguageServer.$anonfun$installedCompilers$1(ScalametaLanguageServer.scala:112)
```

Has anyone else seen this?

**Comment by laughedelic** [comment]
Probably not directly related, but here's another cryptic NPE mentioning `Global`:
<details><summary>Stacktrace</summary>

```
22:13:49.023 ERROR l.c.LanguageServer$$anon$1 - null
java.lang.NullPointerException: null
	at scala.tools.nsc.Global.isPast(Global.scala:986)
	at scala.tools.nsc.Global.isPastTyper(Global.scala:982)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5607)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5798)
	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2287)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5495)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5643)
	at scala.tools.nsc.typechecker.MethodSynthesis$ClassMethodSynthesis.createMethod(MethodSynthesis.scala:45)
	at scala.tools.nsc.typechecker.SyntheticMethods.canEqualMethod$1(SyntheticMethods.scala:133)
	at scala.tools.nsc.typechecker.SyntheticMethods.$anonfun$addSyntheticMethods$19(SyntheticMethods.scala:255)
	at scala.tools.nsc.typechecker.SyntheticMethods.$anonfun$addSyntheticMethods$35(SyntheticMethods.scala:359)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
	at scala.tools.nsc.typechecker.SyntheticMethods.impls$1(SyntheticMethods.scala:359)
	at scala.tools.nsc.typechecker.SyntheticMethods.synthesize$1(SyntheticMethods.scala:374)
	at scala.tools.nsc.typechecker.SyntheticMethods.caseTemplateBody$1(SyntheticMethods.scala:409)
	at scala.tools.nsc.typechecker.SyntheticMethods.$anonfun$addSyntheticMethods$46(SyntheticMethods.scala:413)
	at scala.reflect.internal.Trees.deriveTemplate(Trees.scala:1828)
	at scala.reflect.internal.Trees.deriveTemplate$(Trees.scala:1826)
	at scala.reflect.internal.SymbolTable.deriveTemplate(SymbolTable.scala:16)
	at scala.tools.nsc.typechecker.SyntheticMethods.addSyntheticMethods(SyntheticMethods.scala:412)
	at scala.tools.nsc.typechecker.SyntheticMethods.addSyntheticMethods$(SyntheticMethods.scala:65)
	at scala.tools.nsc.interactive.Global$$anon$4.addSyntheticMethods(Global.scala:219)
	at scala.tools.nsc.typechecker.Typers$Typer.finishMethodSynthesis(Typers.scala:1886)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1812)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5496)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5647)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3086)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3231)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3231)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5207)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5499)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5643)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:104)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
	at scala.tools.nsc.interactive.Global$TyperRun.$anonfun$applyPhase$1(Global.scala:1327)
	at scala.tools.nsc.interactive.Global$TyperRun.applyPhase(Global.scala:1327)
	at scala.tools.nsc.interactive.Global$TyperRun.typeCheck(Global.scala:1320)
	at scala.tools.nsc.interactive.Global.typeCheck(Global.scala:657)
	at scala.tools.nsc.interactive.Global.typedTreeAt(Global.scala:806)
	at scala.meta.languageserver.providers.HoverProvider$.hover(HoverProvider.scala:23)
	at scala.meta.languageserver.ScalametaLanguageServer.$anonfun$hover$1(ScalametaLanguageServer.scala:258)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

**Comment by olafurpg** [comment]
Haven't seen this issue in a while, will close a "unable to reproduce" even if I suspect this issue may appear again.
